### ISSUE TITLE
Could you please provide a document for deployment？

### ISSUE THREAD

**Issue by aloneZERO** [CyC2018/MBlog#6]
群主大大，能否写个部署说明啊，或者说这个项目的部署有没有什么需要注意的地方呢？
因为看到三台服务器和 MySQL 主从复制，感觉还挺复杂的~ :smile:

**Comment by lhy0403** [comment]
Demo 挂掉咯，，

**Comment by CyC2018** [comment]
@lhy0403 这个项目近期不维护了... 现在处于临时开放状态，等一下就关了

**Comment by aloneZERO** [comment]
@CyC2018 只是想学习一些项目中涉及，自己却没怎么接触过的知识，再次给群主点赞 :+1:
